### ISSUE TITLE
Specs

### ISSUE THREAD

**Issue by pedramcodes** [smohadjer/slaven#10]
1. I will need a list of types that could be sent from the form, right now i have only **training** but i need the others so we can validate in backend.
2. Same goes for age_group, right now i have "children" and "adult", is that enough?

**Comment by smohadjer** [comment]
You can see all you need in json schema of the form here:

https://github.com/smohadjer/slaven/blob/master/app/schema/training.json

Does it answer your question? If so, please close the issue.

**Comment by smohadjer** [comment]
@pedramcodes Can we close this issue now?
