### ISSUE TITLE
Value of taining_location

### ISSUE THREAD

**Issue by pedramcodes** [smohadjer/slaven#21]
Please change value of training_location to be an enum, for example _"umkirch"_ or _"zaehringen"_ instead of sending: _TSV+Alemannia+Freiburg+-+Zähringen+e.V._

**Comment by smohadjer** [comment]
I will update schema, the value that form sends is correct.

**Comment by smohadjer** [comment]
Schema is updated. Let me know if you need anything else.

**Comment by smohadjer** [comment]
The value is no longer enumerated. Closing the ticket.
