### ISSUE TITLE
Tennistraining für Gastspieler

### ISSUE THREAD

**Issue by slaven82** [smohadjer/slaven#36]
Für Gäste 3x Training möglich - dann nur als Mitglied.

**Comment by smohadjer** [comment]
Das haben wir schon auf der Seite:

Für Gastspieler ist es möglich drei mal Probetraining zu bekommen. 

Wenn du möchtest den Text verändern, mach einfach so auf GitHub.

**Comment by smohadjer** [comment]
@slaven82 Bitte aktualiesiere den Text auf GitHub and dann die Issue zu machen.
