### ISSUE TITLE
Homepage Link verbindungen

### ISSUE THREAD

**Issue by slaven82** [smohadjer/slaven#38]
Trainingangebot bei TSV Alemannia Zähringen und TC Umkirch.

Können wir in diesem Satz auf der Homepage schon die Worte der vereine als Link machen? Macht das Sinn?

**Comment by slaven82** [comment]
https://www.alemannia-zaehringen.de/tsv_tennis/index.html
https://www.tcumkirch.de/

**Comment by smohadjer** [comment]
Please try to do it yourself and if you run into problem, let me know. After you are done, close the issue.
