### ISSUE TITLE
Überprüf datenschutzerklärung

### ISSUE THREAD

**Issue by smohadjer** [smohadjer/slaven#43]
Diese Datenschutzerklärung gilt für das Internet-Angebot www.slavengluscevic.com. Diese ist für die Inhalte dieses Internet-Angebots verantwortlich. Verweise auf fremde Inhalte sind kenntlich gemacht (s.u.).

Schreib slaven.de statt www.slavengluscevic.com

**Comment by smohadjer** [comment]
@slaven82 Ich habe deine Datenschutzerklärung neu generiert. Dafür habe ich diesen Service benutzt:
https://www.activemind.de/

Bitte überprüf die Seite: https://slaven.de/datenschutz.html

**Comment by slaven82** [comment]
Okay. muss ich hier etwas machen oder nicht?

**Comment by smohadjer** [comment]
Ich weiß nicht. Ich erinnere mich daran dass du wolltest alles mit einem Anwalt durch schauen. Wenn nicht einfach mach es zu.
