### ISSUE TITLE
Store form data in database 

### ISSUE THREAD

**Issue by smohadjer** [smohadjer/slaven#5]
While we won't use data from database on the website in Phase 1, we should still save information to database in case Slaven may need it later.

**Comment by pedramcodes** [comment]
This is now done

**Comment by smohadjer** [comment]
Hi @pedramcodes,

Do not close issues, create a pull request for an issue and let me review it first. When I come to this issue later, I should see clearly what was done to resolve the issue. Can you paste a link to commit in which you resolved this issue?

**Comment by smohadjer** [comment]
Hi @pedramcodes,

Please send me a link which allows me to verify this work. For example an endpoint which when I hit returns me data of all participants.

**Comment by smohadjer** [comment]
Let's put this on back burner for phase 2.
