### ISSUE TITLE
Datenbank - Tabelle

### ISSUE THREAD

**Issue by slaven82** [smohadjer/slaven#51]
Bist du weiter gekommen mit der Tabelle für die Anmeldungen?

**Comment by smohadjer** [comment]
Leider Elissar hat seit Sonntag Influenza und ich könnte nicht arbeiten.

**Comment by smohadjer** [comment]
Wir haben schon eine Issue für dieses Thema hier:
https://github.com/smohadjer/slaven/issues/46

Ich mache diese zu.
